analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml
  rules-exclude:
    - lib/**/injection_injectable.config.dart
    - lib/*.g.dart
    - lib/*.freezed.dart
    - lib/firebase_options.dart
    - test/**
  rules:
    - prefer-match-file-name: false
    - avoid-non-ascii-symbols: false
    - prefer-single-widget-per-file: false
    - no-magic-number: false
    - prefer-moving-to-variable: false
    - avoid-ignoring-return-values: false
    - no-empty-block: false
    - format-comment: false
    - avoid-shrink-wrap-in-lists: false
    - prefer-extracting-callbacks: false
    - no-equal-arguments: false
    - prefer-static-class:
        ignore-private: true
        ignore-names:
          - router
          - getIt
          - (.*)configure(.*)
          - (.*)BottomSheet
    - avoid-late-keyword: false