analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml
  rules-exclude:
    - injection_injectable.config.dart
    - lib/*.g.dart
    - lib/firebase_options.dart
  rules:
    - prefer-match-file-name: false
    - avoid-non-ascii-symbols: false
    - prefer-single-widget-per-file: false
    - no-magic-number: false
    - prefer-moving-to-variable: false
    - avoid-ignoring-return-values: false
    - no-empty-block: false
    - format-comment: false
    - avoid-shrink-wrap-in-lists: false
    - prefer-extracting-callbacks: false