name: sample_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:

  # ----- annotations ------
  
  # freezed 2.2.0
  freezed_annotation:
  
  # json_annotation 4.8.0
  json_annotation:
  
  # retrofit 4.0.1
  retrofit:
  
  # injectable 2.1.1
  injectable:
 
  # ----- dependency injection ----all-

  # get_it 7.2.0
  get_it:


  # ----- network -----

  #dio 5.1.0
  dio:

  # ----- bloc -----

  # flutter_bloc 8.1.2
  flutter_bloc:

  # go_router 7.0.0
  go_router:
  bloc:
  bloc_concurrency:
  mocktail:

  kakao_flutter_sdk_user:

  hive:
  hive_flutter:

  stream_transform: 
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

  #code generate
  hive_generator:
  injectable_generator:
  retrofit_generator:
  freezed:
  build_runner:
  json_serializable:

  # code_metrics 5.7.2
  dart_code_metrics:


flutter:

  uses-material-design: true

 
